### ISSUE TITLE
FIx soxspipe-prep.py script and feedback to AM and JB

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/soxspipe#161]
I was running your script that indeed helps a lot a user willing to reduce X-shooter data with the SoXS pipeline.

I noted a few problems. What can be the reason and eventually a fix?

By the way when are we going to meet?

best regards,

Andrea

problems on SAX data:

1)

sh create_sof_files.sh >> run_pipeline.sh
Traceback (most recent call last):
 File "./soxspipe-prep.py", line 818, in <module>
   main()
 File "./soxspipe-prep.py", line 428, in main
   files = df["file"].values[0]

2)

+---------------------------+------------------------------------------------------------------------------------------+-------------+--------------------------+-------------------------------------------+
|             product_label |                                                                                file_name |   file_type |             obs_date_utc |                              product_desc |
|---------------------------+------------------------------------------------------------------------------------------+-------------+--------------------------+-------------------------------------------|
|        SKY_MODEL_QC_PLOTS | 2019.08.31T00.13.27.1305_NIR_STARE_300PT0_SAX_J1808.43658_SKYMODEL_QC_PLOTS_ORDER_17.pdf |         PDF | 2019-08-31T00:13:27.1305 | QC plots for the sky-background modelling |
|                 SKY_MODEL |                  2019.08.31T00.13.27.1305_NIR_STARE_300PT0_SAX_J1808.43658_SKYMODEL.fits |        FITS | 2019-08-31T00:13:27.1305 |                  The sky background model |
|     SKY_SUBTRACTED_OBJECT |                    2019.08.31T00.13.27.1305_NIR_STARE_300PT0_SAX_J1808.43658_SKYSUB.fits |        FITS | 2019-08-31T00:13:27.1305 |                 The sky-subtracted object |
| SKY SUBTRACTION QUICKLOOK |           2019.08.31T00.13.27.1305_NIR_STARE_300PT0_SAX_J1808.43658_skysub_quicklook.pdf |         PDF | 2019-08-31T00:13:27.1305 |                 Sky-subtraction quicklook |
+---------------------------+------------------------------------------------------------------------------------------+-------------+--------------------------+-------------------------------------------+
# VERIFYING INPUT FRAMES
Traceback (most recent call last):
 File "/scratch/home/amodigli/.conda/envs/soxspipe/bin/soxspipe", line 10, in <module>
   sys.exit(main())
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/cl_utils.py", line 213, in main
   recipe = soxs_stare(
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py", line 85, in __init__
   self.verify_input_frames()
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py", line 133, in verify_input_frames
   raise TypeError(
TypeError: Input frames for soxspipe stare need to be ********* and a master-bias and possibly a master dark for UVB/VIS
# VERIFYING INPUT FRAMES - ALL GOOD

3)

On HD168076 data

The product of this recipe already exists at './product/soxs-mflat/2010.09.14T14.32.09.1137_NIR_MFLAT_90PT0.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
# VERIFYING INPUT FRAMES
Traceback (most recent call last):
 File "/scratch/home/amodigli/.conda/envs/soxspipe/bin/soxspipe", line 10, in <module>
   sys.exit(main())
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/cl_utils.py", line 192, in main
   disp_map, mapImage2D, res_plots = soxs_spatial_solution(
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_spatial_solution.py", line 84, in __init__
   self.verify_input_frames()
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_spatial_solution.py", line 131, in verify_input_frames
   raise TypeError(
TypeError: Input frames for soxspipe spatial_solution need to be LAMP,WAVE lamp on and lamp off frames for NIR
The product of this recipe already exists at './product/soxs-spatial-solution/2010.09.11T18.41.35.9897_NIR_SPAT_SOL_5PT0.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
The product of this recipe already exists at './product/soxs-spatial-solution/2010.09.15T11.25.23.9281_NIR_SPAT_SOL_0PT6651.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
# VERIFYING INPUT FRAMES - ALL GOOD

# PREPARING 7 RAW FRAMES - TRIMMING OVERSCAN, CONVERTING TO ELECTRON COUNTS, GENERATING UNCERTAINTY MAPS AND APPENDING DEFAULT BAD-PIXEL MASK
# PREPARED FRAMES - SUMMARY
                       filename                         INSTRUME    MJD-OBS     ESO DPR TYPE ESO DPR CATG     ESO DPR TECH     ESO SEQ ARM EXPTIME
-------------------------------------------------------- -------- -------------- ------------ ------------ -------------------- ----------- -------
          2010.09.14T13.09.25.7606_NIR_MDARK_20PT0.fits XSHOOTER 55453.54821482           --           --                   --         NIR    20.0
      2010.09.14T15.40.26.6561_NIR_ORDER_LOCATIONS.fits XSHOOTER  55453.6530863           --           --                   --         NIR    40.0
          2010.09.14T15.40.26.6561_NIR_MFLAT_40PT0.fits XSHOOTER  55453.6530863           --           --                   --         NIR    40.0
                 XSHOO.2010-09-14T23:39:32.293_pre.fits XSHOOTER 55453.98579043       OBJECT      SCIENCE ECHELLE,SLIT,NODDING         NIR    20.0
                 XSHOO.2010-09-14T23:40:00.558_pre.fits XSHOOTER 55453.98611757       OBJECT      SCIENCE ECHELLE,SLIT,NODDING         NIR    20.0
     2010.09.15T11.25.23.9281_NIR_SPAT_SOL_0PT6651.fits XSHOOTER 55454.47597139           --           --                   --         NIR  0.6651
2010.09.15T11.25.23.9281_NIR_SPAT_SOL_0PT6651_IMAGE.fits XSHOOTER 55454.47597139           --           --                   --         NIR  0.6651
* 09:14:22 - WARNING: /scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py:produce_product:206 > Processing a NODDING frame with the stare-mode recipe
Traceback (most recent call last):
 File "/scratch/home/amodigli/.conda/envs/soxspipe/bin/soxspipe", line 10, in <module>
   sys.exit(main())
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/cl_utils.py", line 221, in main
   reducedStare = recipe.produce_product()
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py", line 208, in produce_product
   combined_object = self.clip_and_stack(
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/_base_recipe_.py", line 792, in clip_and_stack
   imageType = ccds[0].header[kw("DPR_TYPE")].replace(",", "-")
IndexError: list index out of range
# VERIFYING INPUT FRAMES
Traceback (most recent call last):
 File "/scratch/home/amodigli/.conda/envs/soxspipe/bin/soxspipe", line 10, in <module>
   sys.exit(main())
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/cl_utils.py", line 213, in main
   recipe = soxs_stare(
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py", line 85, in __init__
   self.verify_input_frames()
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py", line 127, in verify_input_frames
   raise TypeError(
TypeError: Input frames for soxspipe stare need to be ********* lamp on and lamp off frames for NIR
# VERIFYING INPUT FRAMES - ALL GOOD

# PREPARING 7 RAW FRAMES - TRIMMING OVERSCAN, CONVERTING TO ELECTRON COUNTS, GENERATING UNCERTAINTY MAPS AND APPENDING DEFAULT BAD-PIXEL MASK
# PREPARED FRAMES - SUMMARY
                       filename                         INSTRUME    MJD-OBS     ESO DPR TYPE ESO DPR CATG     ESO DPR TECH     ESO SEQ ARM EXPTIME
-------------------------------------------------------- -------- -------------- ------------ ------------ -------------------- ----------- -------
          2010.09.14T13.09.25.7606_NIR_MDARK_20PT0.fits XSHOOTER 55453.54821482           --           --                   --         NIR    20.0
      2010.09.14T15.40.26.6561_NIR_ORDER_LOCATIONS.fits XSHOOTER  55453.6530863           --           --                   --         NIR    40.0
          2010.09.14T15.40.26.6561_NIR_MFLAT_40PT0.fits XSHOOTER  55453.6530863           --           --                   --         NIR    40.0
                 XSHOO.2010-09-14T23:39:32.293_pre.fits XSHOOTER 55453.98579043       OBJECT      SCIENCE ECHELLE,SLIT,NODDING         NIR    20.0
                 XSHOO.2010-09-14T23:40:00.558_pre.fits XSHOOTER 55453.98611757       OBJECT      SCIENCE ECHELLE,SLIT,NODDING         NIR    20.0
     2010.09.15T11.25.23.9281_NIR_SPAT_SOL_0PT6651.fits XSHOOTER 55454.47597139           --           --                   --         NIR  0.6651
2010.09.15T11.25.23.9281_NIR_SPAT_SOL_0PT6651_IMAGE.fits XSHOOTER 55454.47597139           --           --                   --         NIR  0.6651
* 09:14:25 - WARNING: /scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py:produce_product:206 > Processing a NODDING frame with the stare-mode recipe
Traceback (most recent call last):
 File "/scratch/home/amodigli/.conda/envs/soxspipe/bin/soxspipe", line 10, in <module>
   sys.exit(main())
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/cl_utils.py", line 221, in main
   reducedStare = recipe.produce_product()
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py", line 208, in produce_product
   combined_object = self.clip_and_stack(
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/_base_recipe_.py", line 792, in clip_and_stack
   imageType = ccds[0].header[kw("DPR_TYPE")].replace(",", "-")
IndexError: list index out of range
# VERIFYING INPUT FRAMES
Traceback (most recent call last):
 File "/scratch/home/amodigli/.conda/envs/soxspipe/bin/soxspipe", line 10, in <module>
   sys.exit(main())
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/cl_utils.py", line 213, in main
   recipe = soxs_stare(
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py", line 85, in __init__
   self.verify_input_frames()
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py", line 127, in verify_input_frames
   raise TypeError(
TypeError: Input frames for soxspipe stare need to be ********* lamp on and lamp off frames for NIR
The product of this recipe already exists at './product/soxs-mdark/2010.09.14T13.09.25.7606_NIR_MDARK_20PT0.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
The product of this recipe already exists at './product/soxs-disp-solution/2010.09.11T18.37.40.9255_NIR_DISP_SOL_10PT0.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
The product of this recipe already exists at './product/soxs-disp-solution/2010.09.15T11.08.13.0776_NIR_DISP_SOL_10PT0.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
The product of this recipe already exists at './product/soxs-order-centre/2010.09.11T17.33.44.4844_NIR_ORDER_LOCATIONS_1PT0.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
The product of this recipe already exists at './product/soxs-order-centre/2010.09.15T11.23.15.8716_NIR_ORDER_LOCATIONS_1PT0.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
The product of this recipe already exists at './product/soxs-mflat/2010.09.11T18.21.01.9071_NIR_MFLAT_80PT0.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
The product of this recipe already exists at './product/soxs-mflat/2010.09.14T15.40.26.6561_NIR_MFLAT_40PT0.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
The product of this recipe already exists at './product/soxs-mflat/2010.09.11T14.48.05.4317_NIR_MFLAT_7PT2.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
The product of this recipe already exists at './product/soxs-mflat/2010.09.14T14.32.09.1137_NIR_MFLAT_90PT0.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
The product of this recipe already exists at './product/soxs-mflat/2010.09.15T14.22.15.1905_NIR_MFLAT_7PT2.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
The product of this recipe already exists at './product/soxs-spatial-solution/2010.09.11T18.41.35.9897_NIR_SPAT_SOL_5PT0.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
# VERIFYING INPUT FRAMES
Traceback (most recent call last):
 File "/scratch/home/amodigli/.conda/envs/soxspipe/bin/soxspipe", line 10, in <module>
   sys.exit(main())
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/cl_utils.py", line 192, in main
   disp_map, mapImage2D, res_plots = soxs_spatial_solution(
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_spatial_solution.py", line 84, in __init__
   self.verify_input_frames()
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_spatial_solution.py", line 131, in verify_input_frames
   raise TypeError(
TypeError: Input frames for soxspipe spatial_solution need to be LAMP,WAVE lamp on and lamp off frames for NIR
The product of this recipe already exists at './product/soxs-spatial-solution/2010.09.15T11.25.23.9281_NIR_SPAT_SOL_0PT6651.fits'. To overwrite this product, rerun the pipeline command with the overwrite flag (-x).
# VERIFYING INPUT FRAMES - ALL GOOD

# PREPARING 7 RAW FRAMES - TRIMMING OVERSCAN, CONVERTING TO ELECTRON COUNTS, GENERATING UNCERTAINTY MAPS AND APPENDING DEFAULT BAD-PIXEL MASK
# PREPARED FRAMES - SUMMARY
                       filename                         INSTRUME    MJD-OBS     ESO DPR TYPE ESO DPR CATG     ESO DPR TECH     ESO SEQ ARM EXPTIME
-------------------------------------------------------- -------- -------------- ------------ ------------ -------------------- ----------- -------
          2010.09.14T13.09.25.7606_NIR_MDARK_20PT0.fits XSHOOTER 55453.54821482           --           --                   --         NIR    20.0
      2010.09.14T15.40.26.6561_NIR_ORDER_LOCATIONS.fits XSHOOTER  55453.6530863           --           --                   --         NIR    40.0
          2010.09.14T15.40.26.6561_NIR_MFLAT_40PT0.fits XSHOOTER  55453.6530863           --           --                   --         NIR    40.0
                 XSHOO.2010-09-14T23:39:32.293_pre.fits XSHOOTER 55453.98579043       OBJECT      SCIENCE ECHELLE,SLIT,NODDING         NIR    20.0
                 XSHOO.2010-09-14T23:40:00.558_pre.fits XSHOOTER 55453.98611757       OBJECT      SCIENCE ECHELLE,SLIT,NODDING         NIR    20.0
     2010.09.15T11.25.23.9281_NIR_SPAT_SOL_0PT6651.fits XSHOOTER 55454.47597139           --           --                   --         NIR  0.6651
2010.09.15T11.25.23.9281_NIR_SPAT_SOL_0PT6651_IMAGE.fits XSHOOTER 55454.47597139           --           --                   --         NIR  0.6651
* 09:14:35 - WARNING: /scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py:produce_product:206 > Processing a NODDING frame with the stare-mode recipe
Traceback (most recent call last):
 File "/scratch/home/amodigli/.conda/envs/soxspipe/bin/soxspipe", line 10, in <module>
   sys.exit(main())
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/cl_utils.py", line 221, in main
   reducedStare = recipe.produce_product()
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py", line 208, in produce_product
   combined_object = self.clip_and_stack(
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/_base_recipe_.py", line 792, in clip_and_stack
   imageType = ccds[0].header[kw("DPR_TYPE")].replace(",", "-")
IndexError: list index out of range
# VERIFYING INPUT FRAMES
Traceback (most recent call last):
 File "/scratch/home/amodigli/.conda/envs/soxspipe/bin/soxspipe", line 10, in <module>
   sys.exit(main())
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/cl_utils.py", line 213, in main
   recipe = soxs_stare(
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py", line 85, in __init__
   self.verify_input_frames()
 File "/scratch/home/amodigli/.conda/envs/soxspipe/lib/python3.8/site-packages/soxspipe/recipes/soxs_stare.py", line 127, in verify_input_frames
   raise TypeError(
TypeError: Input frames for soxspipe stare need to be ********* lamp on and lamp off frames for NIR

-----------------------------------

The data I tested on are:

raw_frames/XSHOO.2019-08-31T00:13:27.131.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:13:29.027.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:13:29.038.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:21:31.523.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:21:33.007.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:21:33.008.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:29:34.585.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:29:36.008.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:29:36.009.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:37:40.307.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:37:42.010.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:37:42.011.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:45:43.370.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:45:45.001.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:45:45.002.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:53:47.099.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:53:48.002.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T00:53:48.003.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:01:49.495.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:01:51.004.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:01:51.005.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:11:18.959.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:11:20.002.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:11:20.003.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:19:21.356.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:19:23.003.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:19:23.004.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:27:24.419.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:27:26.004.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:27:26.005.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:35:27.481.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:35:29.019.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:35:29.020.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:43:30.542.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:43:32.007.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:43:32.008.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:51:33.606.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:51:35.008.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:51:35.009.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:59:36.669.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:59:38.010.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T01:59:38.011.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:09:24.754.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:09:27.010.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:09:27.011.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:17:28.483.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:17:30.002.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:17:30.003.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:25:31.545.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:25:33.003.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:25:33.004.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:33:34.608.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:33:36.005.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:33:36.006.fits           SCIENCE         VIS             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:41:38.336.fits           SCIENCE         NIR             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:41:40.005.fits           SCIENCE         UVB             SAX J1808.4--3658
raw_frames/XSHOO.2019-08-31T02:41:40.007.fits           SCIENCE         VIS             SAX J1808.4--3658

and

raw_frames/XSHOO.2010-09-14T23:39:32.293.fits           SCIENCE         NIR             HD168076      
raw_frames/XSHOO.2010-09-14T23:40:00.558.fits           SCIENCE         NIR             HD168076      
raw_frames/XSHOO.2010-09-14T23:41:30.310.fits           SCIENCE         NIR             HD168076      
raw_frames/XSHOO.2010-09-14T23:41:58.573.fits           SCIENCE         NIR             HD168076

**Comment by thespacedoctor** [comment]
Going to bypass this issue and fix by releasing a beta version of the data-organiser.
